### ISSUE TITLE
torch value Error in training

### ISSUE THREAD

**Issue by Jrebort** [vitoralbiero/img2pose#45]
I am runing the command:
```
python3 -m torch.distributed.launch --nproc_per_node=4 --use_env train.py \
--pose_mean ./datasets/lmdb/WIDER_train_annotations_pose_mean.npy \
--pose_stddev ./datasets/lmdb/WIDER_train_annotations_pose_stddev.npy \
--workspace ./workspace/ \
--train_source ./datasets/lmdb/WIDER_train_annotations.lmdb \
--val_source ./datasets/lmdb/WIDER_val_annotations.lmdb \
--prefix trial_1 \
--batch_size 2 \
--lr_plateau \
--early_stop \
--random_flip \
--random_crop \
--max_size 1400 \
--distributed
```

Having a issue:
Traceback (most recent call last):
  File "train.py", line 403, in <module>
    train.run()
  File "train.py", line 151, in run
    losses = self.img2pose_model.forward(imgs, targets)
  File "/data/x/img2pose/img2pose.py", line 127, in forward
    losses = self.run_model(imgs, targets)
  File "/data/x/img2pose/img2pose.py", line 122, in run_model
    outputs = self.fpn_model(imgs, targets)
  File "/home/x/.conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/x/.conda/envs/py38/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/x/.conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/x/img2pose/generalized_rcnn.py", line 79, in forward
    images, targets = self.transform(images, targets)
  File "/home/x/.conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/x/.conda/envs/py38/lib/python3.8/site-packages/torchvision/models/detection/transform.py", line 105, in forward
    image, target_index = self.resize(image, target_index)
  File "/home/x/.conda/envs/py38/lib/python3.8/site-packages/torchvision/models/detection/transform.py", line 140, in resize
    size = float(self.torch_choice(self.min_size))
ValueError: could not convert string to float: '640, 672, 704, 736, 768, 800'

**Comment by vitoralbiero** [comment]
Hello @Jrebort,

Thanks for flagging this.
Please run git pull and try again as I have just pushed a fixed for this problem. 
If you still have an issue, feel free to re-open this issue.
